{
 "title": "ace2-g9-dashboard",
 "time": { "from": "2024-10-19T03:37:26.000Z", "to": "2024-10-19T03:44:56.000Z" },
 "refresh": "1d",
 "panels": [
  {
   "title": "Temperatura",
   "type": "gauge",
   "description": "La gráfica de Gauge muestra la temperatura actual en grados Celsius, proporcionando una visualización clara y rápida de las condiciones térmicas. Este medidor utiliza un rango de temperatura de 0°C a 50°C.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ace2",
     "rawSql": "SELECT temperatura FROM ace2.lecturas ORDER BY fecha DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Iluminación",
   "type": "bargauge",
   "description": "La gráfica de Gauge mide el nivel de luz en el entorno, con un rango de 0 lux a 1024 lux. Este medidor proporciona una visualización intuitiva de la intensidad de la luz, permitiendo una rápida evaluación de las condiciones lumínicas en diferentes situaciones.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ace2",
     "rawSql": "SELECT luz FROM ace2.lecturas ORDER BY fecha DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Proximidad",
   "type": "bargauge",
   "description": "La gráfica mide la proximidad de un objeto en un rango de 2 cm a 8 metros. Este medidor permite visualizar de manera clara y rápida la distancia actual entre el sensor y un objeto, lo que es útil en diversas aplicaciones como la robótica, sistemas de seguridad o estacionamiento.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ace2",
     "rawSql": "SELECT proximidad FROM ace2.lecturas ORDER BY fecha DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Humedad",
   "type": "stat",
   "description": "La gráfica mide el porcentaje de humedad relativa en el ambiente, con un rango de 0% a 100%. La humedad relativa es un indicador del contenido de vapor de agua en el aire, y este medidor proporciona una manera rápida y clara de visualizar el nivel de humedad actual.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ace2",
     "rawSql": "SELECT humedad, fecha FROM ace2.lecturas ORDER BY fecha ASC LIMIT 10 "
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "description": "La gráfica muestra la evolución de los niveles de dióxido de carbono (CO₂) en el ambiente a lo largo del tiempo, con un rango de 10 ppm a 1000 ppm. Esta métrica es crucial para evaluar la calidad del aire en espacios cerrados o abiertos, donde la acumulación de CO₂ puede tener efectos importantes en la salud y el confort.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "dataset": "ace2",
     "rawSql": "SELECT co2, fecha FROM ace2.lecturas ORDER BY fecha ASC LIMIT 10 "
    }
   ]
  }
 ]
}