DROP DATABASE IF EXISTS FASE2_ARQUI2;
CREATE DATABASE FASE2_ARQUI2;
USE FASE2_ARQUI2;

/* - TABLAS - */
CREATE TABLE TEMPERATURA (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    VALOR DECIMAL(5,2) NOT NULL,
    FECHA DATE NOT NULL
);

CREATE TABLE HUMEDAD (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    VALOR DECIMAL(5,2) NOT NULL,
    FECHA DATE NOT NULL
);

CREATE TABLE LUZ (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    VALOR DECIMAL(5,2) NOT NULL,
    FECHA DATE NOT NULL
);

CREATE TABLE CO2 (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    VALOR DECIMAL(5,2) NOT NULL,
    FECHA DATE NOT NULL
);

CREATE TABLE PROXIMIDAD (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    VALOR DECIMAL(5,2) NOT NULL,
    FECHA DATE NOT NULL
);

SHOW TABLES;